import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { DatabaseService } from '../../common/database/database.service';
import { CreateGhostwriterDraftDto } from './dto/create-ghostwriter-draft.dto';
import { FingerprintPayload } from '../fingerprints/types/fingerprint.types';

@Injectable()
export class GhostwriterService {
  constructor(private readonly database: DatabaseService) {}

  async listForNewsletter(userId: string, newsletterId: string) {
    await this.verifyNewsletterAccess(userId, newsletterId);
    return this.database.ghostwriterDraft.findMany({
      where: { newsletterId },
      orderBy: { createdAt: 'desc' },
    });
  }

  async create(userId: string, newsletterId: string, dto: CreateGhostwriterDraftDto) {
    const newsletter = await this.database.newsletter.findUnique({
      where: { id: newsletterId },
      include: { fingerprint: true },
    });
    if (!newsletter) {
      throw new NotFoundException(`Newsletter ${newsletterId} not found`);
    }
    if (newsletter.userId !== userId) {
      throw new ForbiddenException('You do not have access to this newsletter');
    }
    if (!newsletter.fingerprint || newsletter.fingerprint.status !== 'READY') {
      throw new BadRequestException(
        'Generate a fingerprint before using the ghostwriter',
      );
    }
    const fingerprint = this.parseFingerprint(newsletter.fingerprint);
    const content = this.composeDraft(newsletter.name, fingerprint, dto);
    return this.database.ghostwriterDraft.create({
      data: {
        newsletterId,
        fingerprintId: newsletter.fingerprint.id,
        title: dto.title,
        outline: dto.outline ?? [],
        content,
      },
    });
  }

  async findOne(userId: string, newsletterId: string, draftId: string) {
    await this.verifyNewsletterAccess(userId, newsletterId);
    const draft = await this.database.ghostwriterDraft.findFirst({
      where: { id: draftId, newsletterId },
    });
    if (!draft) {
      throw new NotFoundException(`Draft ${draftId} not found`);
    }
    return draft;
  }

  private async verifyNewsletterAccess(userId: string, newsletterId: string): Promise<void> {
    const newsletter = await this.database.newsletter.findUnique({
      where: { id: newsletterId },
      select: { userId: true },
    });
    if (!newsletter) {
      throw new NotFoundException(`Newsletter ${newsletterId} not found`);
    }
    if (newsletter.userId !== userId) {
      throw new ForbiddenException('You do not have access to this newsletter');
    }
  }

  private parseFingerprint(record: {
    topics: Prisma.JsonValue;
    voice: Prisma.JsonValue;
    audience: Prisma.JsonValue;
    depthFormat: Prisma.JsonValue;
    obsessions: Prisma.JsonValue;
    summary: string | null;
  }): FingerprintPayload {
    return {
      topics: (record.topics as unknown as FingerprintPayload['topics']) ?? [],
      voice: (record.voice as unknown as FingerprintPayload['voice']) ?? {
        tone: 'Neutral',
        formality: 'Conversational',
        sentenceRhythm: 'Balanced',
        humor: 'Minimal',
        signaturePhrases: [],
      },
      audience: (record.audience as unknown as FingerprintPayload['audience']) ?? {
        profile: 'Newsletter readers',
        expertiseLevel: 'Generalist',
        motivations: [],
      },
      depthFormat: (record.depthFormat as unknown as FingerprintPayload['depthFormat']) ?? {
        typicalLength: 'Medium',
        technicalDepth: 'Balanced',
        structure: 'Hook → body → close',
        avgWordsPerIssue: 700,
        avgSentencesPerIssue: 40,
      },
      obsessions: (record.obsessions as unknown as FingerprintPayload['obsessions']) ?? [],
      summary: record.summary ?? '',
    };
  }

  private composeDraft(
    newsletterName: string,
    fingerprint: FingerprintPayload,
    dto: CreateGhostwriterDraftDto,
  ): string {
    const leadTopic = fingerprint.topics[0]?.name ?? 'your core theme';
    const outline = dto.outline?.length
      ? dto.outline
      : [
          `Open with a ${fingerprint.voice.tone.toLowerCase()} hook on ${leadTopic}`,
          `Develop the argument in a ${fingerprint.voice.formality.toLowerCase()} voice`,
          'Land a concrete takeaway the reader can act on this week',
        ];
    const sections = outline
      .map((item, index) => `## ${index + 1}. ${item}\n\n[Draft this section in ${newsletterName}'s voice — ${fingerprint.voice.sentenceRhythm.toLowerCase()}. Emphasize ${leadTopic}.]`)
      .join('\n\n');
    const briefBlock = dto.brief
      ? `\n\n> Creator brief: ${dto.brief}\n`
      : '';
    return `# ${dto.title}\n${briefBlock}\n${fingerprint.summary}\n\n${sections}\n\n---\n\n*Draft generated by LoopTilt Ghostwriter (v1). Voice profile: ${fingerprint.voice.tone}, ${fingerprint.voice.formality}. Typical length: ${fingerprint.depthFormat.typicalLength}.*`;
  }
}
